env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_config: "ENCRYPTED[0e7d7645f4d1f66aaf71253489560e43fd562bf830081c6a75e7747d70df9f3bd34e3b607ff9967418dbd708f398e92c]"
    bot_api: ""

task:
  name: GIT
  timeout_in: 5m
  container:
    image: apon77/aosp:latest
    cpu: .7
    memory: 2G
  git_clone_repo_script:
    - rm -rf download_ccache sync monitor build upload_ccache
    - git clone -b LineageOS-18.1-Bak --single-branch https://github.com/dopaemon/AOSP.git
    - cd AOSP
    - sudo chmod +x *
    - mv * ../
    - cd ..
    - rm -rf AOSP
  script_builder:
    - cat build 
  telegram:
    - rom_name=$(grep init build -m 1 | cut -d / -f 4)
    - device=$(grep unch build -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)
    - your_telegram_id=@KernelPanic_OpenSource_CI
    - show=$(cat build)
    - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" -d "text=<code>$device-$rom_name</code> Started
      https://cirrus-ci.com/build/$CIRRUS_BUILD_ID
      $show" -d "chat_id=${your_telegram_id}" -d "parse_mode=HTML"
task:
  name: ccache
  timeout_in: 5m
  depends_on:
    - GIT
  container:
    image: apon77/aosp:latest
    cpu: .7
    memory: 2G
  download_ccache_background_script:
    - ./download_ccache
task:
  name: build
  timeout_in: 2h
  depends_on:
    - ccache
  container:
    image: apon77/aosp:latest
    cpu: 8
    memory: 32G
  sync_script:
    - ./sync
  monitor_background_script:
    - ./monitor
  build_script:
    - ./build
  build_done:
    - rom_name=$(grep init build -m 1 | cut -d / -f 4)
    - device=$(grep unch build -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)
    - your_telegram_id=@KernelPanic_OpenSource_CI
    - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" -d "text=<code>$device-$rom_name</code> Succeed
      https://cirrus-ci.com/build/$CIRRUS_BUILD_ID" -d "chat_id=${your_telegram_id}" -d "parse_mode=HTML"
task:
  name: Upload
  timeout_in: 30m
  depends_on:
    - build
  container:
    image: apon77/aosp:latest
    cpu: 4
    memory: 5G
  upload_ccache_script:
    - ./upload
