env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_config: "ENCRYPTED[b665ada45afc9a8754057372d1168f1e3cc1b3302a08cb4ce8f2f424ce4e64c8c77544c4d42e180be0890bca47109000]"
    bot_api: "ENCRYPTED[890d5b9d7c5fcabe7539258296ebdc053a99637accf12cc651aa958f7217a02b80f06d3a244cb8a212746ce4209b1119]"

task:
  name: Test Build
  timeout_in: 2h
  container:
    image: apon77/aosp:latest
    cpu: 8
    memory: 32G
  git_clone_repo_script:
    - rm -rf download_ccache sync monitor build upload_ccache
    - git clone -b main --single-branch https://github.com/dopaemon/AOSP.git
    - cd AOSP
    - sudo chmod +x *
    - mv * ../
    - cd ..
    - rm -rf AOSP
  script_builder:
    - cat build 
  telegram:
    - rom_name=$(grep init build -m 1 | cut -d / -f 4)
    - device=$(grep unch build -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)
    - your_telegram_id=@KernelPanic_OpenSource_CI
    - show=$(cat build)
    - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" -d "text=<code>$device-$rom_name</code> Started
      https://cirrus-ci.com/build/$CIRRUS_BUILD_ID
      $show" -d "chat_id=${your_telegram_id}" -d "parse_mode=HTML"
  sync_script:
    - ./sync
  monitor_background_script:
    - ./monitor
  build_script:
    - ./build
  build_done:
    - rom_name=$(grep init build -m 1 | cut -d / -f 4)
    - device=$(grep unch build -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)
    - your_telegram_id=@KernelPanic_OpenSource_CI
    - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" -d "text=<code>$device-$rom_name</code> Succeed
      https://cirrus-ci.com/build/$CIRRUS_BUILD_ID" -d "chat_id=${your_telegram_id}" -d "parse_mode=HTML"
  upload_ccache_script:
    - ./upload
