env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_config: "ENCRYPTED[b15a6c4c98b97843170eb58a96e93ff70c1125cdb6109e3ea5760d3674f0b0a3086b379e477abdd4b55fcc31637c107c]"

task:
    name: LineageOS-18.1
    timeout_in: 120m
    container:
        image: dopaemon/android2:latest
        cpu: 8
        memory: 32G
    download_ccache_background_script:
      - ./download_ccache
    sync_script:
      - ./sync
    monitor_background_script:
      - ./monitor
    build_script:
      - ./build
    upload_ccache_script:
      - ./upload_ccache
