env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_config: "ENCRYPTED[8c45e16acc0699194b0b4e697ab1e23a1fb263bf99699af5068a73880dabcd5b91ebda59b0a5865bbb905e5a542123df]"
    bot_api: "ENCRYPTED[890d5b9d7c5fcabe7539258296ebdc053a99637accf12cc651aa958f7217a02b80f06d3a244cb8a212746ce4209b1119]"

task:
  name: Build_Upload
  timeout_in: 2h
  container:
    image: apon77/aosp:latest
    cpu: 8
    memory: 32G
  chmod_script:
    - sudo chmod +x *
  telegram_script:
    - ./telegram
  sync_script:
    - ./sync
  monitor_background_script:
    - ./monitor
  build_script:
    - ./build
  upload_ccache_script:
    - ./upload
