env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
task:
  persistent_worker:
    labels:
      os: linux
      arch: amd64
  script: echo "running on-premise"
  name: Build_Upload
  timeout_in: 2h
  container:
    image: apon77/aosp:latest
    cpu: 8
    memory: 32G
  chmod_script:
    - sudo chmod +x *
  sync_script:
    - ./sync
  monitor_background_script:
    - ./monitor
  build_script:
    - ./build
