env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_config: "ENCRYPTED[52ba5b781cdddab2370f378967c038411d5d343339beaa42bde862925a5f975dfbbb761566b5021f77b27cbfa6c37e16]"

task:
    name: LineageOS-18.1 # Build 1
    timeout_in: 120m
    container:
        image: apon77/aosp:latest
        cpu: 8
        memory: 32G
    git_clone_repo_script:
      - rm -rf download_ccache sync monitor build upload_ccache
      - git clone -b LineageOS-18.1-Bak --single-branch https://github.com/KernelPanic-OpenSource/AOSP
      - cd AOSP
      - sudo chmod +x *
      - mv * ../
      - cd ..
      - rm -rf AOSP
    download_ccache_background_script:
      - ./download_ccache
    sync_script:
      - ./sync
    monitor_background_script:
      - ./monitor
    build_script:
      - ./build
    upload_ccache_script:
      - ./upload_ccache
