env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_config: "ENCRYPTED[b665ada45afc9a8754057372d1168f1e3cc1b3302a08cb4ce8f2f424ce4e64c8c77544c4d42e180be0890bca47109000]"
    bot_api: "ENCRYPTED[890d5b9d7c5fcabe7539258296ebdc053a99637accf12cc651aa958f7217a02b80f06d3a244cb8a212746ce4209b1119]"

task:
  name: Telegram
  timeout_in: 5m
  container:
    image: apon77/aosp:latest
    cpu: .7
    memory: 1G
  telegram:
    - ./telegram
task:
  name: Build_Upload
  timeout_in: 2h
  depends_on:
    - Telegram
  container:
    image: apon77/aosp:latest
    cpu: 8
    memory: 32G
  sync_script:
    - ./sync
  monitor_background_script:
    - ./monitor
  build_script:
    - ./build
  upload_ccache_script:
    - ./upload
