env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    BUILD_HOSTNAME: "e8f486553f26"
    
task:
  persistent_worker:
    labels:
      os: linux
      arch: amd64
      name: AOSP
      
  name: AOSP
  timeout_in: 4h
  container:
    image: apon77/aosp:latest
    cpu: 8
    memory: 32G
  chmod_script:
    - whoami
    - sudo chmod +x *
  sync_script:
    - ./sync
  monitor_background_script:
    - ./monitor
  build_script:
    - ./build
